language: cpp
dist: xenial
notifications:
  email: false


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - g++-7
      env:
        - C_COMPILER="gcc-7", CXX_COMPILER="g++-7"

before_install:
  - pyenv global $(pyenv whence 2to3)
  - pip install pipenv

  - echo "Downloading OpenMPI Source"
  - wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.3.tar.gz
  - tar zxf openmpi-3.1.3.tar.gz
  - echo "Configuring and building OpenMPI"
  - mkdir -p $TRAVIS_BUILD_DIR/openmpi-build
  - cd openmpi-3.1.3
  - export CC=$C_COMPILER
  - export CXX=$CXX_COMPILER
  - ./configure --prefix=$TRAVIS_BUILD_DIR/openmpi-build &> mpi.configure.log
  - make -j3 &> mpi.make.log
  - make install &> mpi.make.install.log
  - cd ..
  - export MPI_CC=$TRAVIS_BUILD_DIR/openmpi-build/bin/mpicc
  - export MPI_CXX=$TRAVIS_BUILD_DIR/openmpi-build/bin/mpic++
  - export MPI_EXEC=$TRAVIS_BUILD_DIR/openmpi-build/bin/mpiexec
    
  # Disable CC and CXX, which interferes with MPI
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

  - $MPI_CXX --version

install:
  - env MPICC=$MPI_CC pipenv install

script:
  # Build C++ program.
  - $MPI_CXX -std=c++17 hello_mpi.cpp -o hello
  # Run C++ program. Travis may not have 2 cores available. Try with 2, if fail do 1.
  - $MPI_EXEC -n 2 ./hello || $MPI_EXEC -n 1 ./hello
  # Run mpi4py based program.
  - $MPI_EXEC -n 2 pipenv run python hello_mpi.py || $MPI_EXEC -n 1 pipenv run python hello_mpi.py

