language: cpp
dist: xenial
notifications:
  email: false


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.7-dev
            - g++-7
      env:
        - C_COMPILER="gcc-7", CXX_COMPILER="g++-7"

before_install:
  - pyenv global $(pyenv whence 2to3)
  - pip install pipenv

  - echo "Downloading OpenMPI Source"
  - wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.3.tar.gz
  - tar zxf openmpi-3.1.3.tar.gz
  - echo "Configuring and building OpenMPI"
  - mkdir -p $TRAVIS_BUILD_DIR/openmpi-build
  - cd openmpi-3.1.3
  - export CC=$C_COMPILER
  - export CXX=$CXX_COMPILER
  - ./configure --prefix=$TRAVIS_BUILD_DIR/openmpi-build 
  - make -j3 
  - make install
  - cd ..
    
  # Disable CC and CXX, which interferes with MPI
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

  - $TRAVIS_BUILD_DIR/openmpi-build/bin/mpic++ --version
  - env MPICC=$TRAVIS_BUILD_DIR/openmpi-build/bin/mpicc pip install mpi4py

install:
  - $TRAVIS_BUILD_DIR/openmpi-build/bin/mpic++ -std=c++17 hello_mpi.cpp -o hello

script:
  - mpiexec -n 1 ./hello
  - mpiexec -n 2 ./hello
  - mpiexec -n 1 pipenv run python hello_mpi.py
  - mpiexec -n 2 pipenv run python hello_mpi.py

