language: cpp
dist: xenial
notifications:
  email: false

- os: linux
  addons:
    apt:
      sources:
        - deadsnakes
        - ubuntu-toolchain-r-test
      packages:
        - python3.7-dev
        - gcc-7, g++-7
        - libopenmpi-dev, openmpi-bin, libhdf5-openmpi-dev
  env:
    - C_COMPILER="gcc-7"
    - CXX_COMPILER="g++-7"


before_install:
  - pyenv global $(pyenv whence 2to3)
  - pip install pipenv

  # Disable CC and CXX, which interferes with MPI
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

  - mpic++ --version

install:
  - mpic++ -std=c++17 hello_mpi.cpp -o hello
  - pipenv install  # Installs mpi4py.

script:
  - mpiexec -n 1 ./hello
  - mpiexec -n 2 ./hello
  - mpiexec -n 1 pipenv run python hello_mpi.py
  - mpiexec -n 2 pipenv run python hello_mpi.py

